### ISSUE TITLE
returned value never checked.

### ISSUE THREAD

**Issue by yuriy77k** [Dexaran/TokenStandardConverter#1]
The function `tokenReceived` returns `magic number`:
https://github.com/Dexaran/TokenStandardConverter/blob/c740ceceed8acb632f16b411bcd0b14098f4493d/TokenConverter.sol#L112-L120

But in the only place where this return value can be checked ignore it.
https://github.com/Dexaran/TokenStandardConverter/blob/c740ceceed8acb632f16b411bcd0b14098f4493d/TokenConverter.sol#L67-L69

**Comment by Dexaran** [comment]
If we want to make token work identical to Ether transfers we should not FORCE devs to `revert()` if the return value is not `magic number`

For ETH transfers it works like this:

1. It can be handled by a payable function

2. It can be handled by a payable fallback function

3. It can be handled by a payable `receive()` function without returns

All 3 cases are valid.

So I guess for ERC-223 transfers we should not assume that if ERC-223 transfer was handled by a fallback function then it is 100% wrong. If someone wants to write a contract that accepts everything (such as multisig) then it should work. Also it will make ERC-223 transfers compatible with old multisigs designed to receive Ether.

However it may be necessary for a developer (in some cases) to check if the token transfer was handled by the fallback function or a `tokenReceived()` of ERC-223. In this case the return value can be used.

**Comment by yuriy77k** [comment]
Then what sense of returned magic number? I don't mean the ERC223 standard, I mean this particular implementation, where `ret` is assigned and never used.

**Comment by Dexaran** [comment]
Compatibility with the standard. We must expect the `bytes4 return` but we ignore it in case of this token. Because the contract is general purpose and we don't really know if this tokens must be compatible with contracts with permissive fallback function or not.

**Comment by Dexaran** [comment]
We can remove the assignment however. It was just copy&pasted from the standard reference implementation so in this particular contract it makes no sense.
