### ISSUE TITLE
Unnecessary code 

### ISSUE THREAD

**Issue by yuriy77k** [Dexaran/TokenStandardConverter#10]
1. The wrapper token contract can't call `transferFrom` in itself, so this can be removed:
- https://github.com/Dexaran/TokenStandardConverter/blob/5690be8dfb80903d0ea5d553f20b266baf503549/TokenConverter.sol#L163
- https://github.com/Dexaran/TokenStandardConverter/blob/5690be8dfb80903d0ea5d553f20b266baf503549/TokenConverter.sol#L250

2. The variable `wrapper_for` should be private (to avoid generating a useless getter function), since the getter `function origin()      public view returns (address)                { return wrapper_for; }` already exists.
- https://github.com/Dexaran/TokenStandardConverter/blob/5690be8dfb80903d0ea5d553f20b266baf503549/TokenConverter.sol#L188
- https://github.com/Dexaran/TokenStandardConverter/blob/5690be8dfb80903d0ea5d553f20b266baf503549/TokenConverter.sol#L76

3. The variable `balances` should be private (to avoid generating a useless getter function), since the getter `function balanceOf(address _owner) public view override returns (uint256) { return balances[_owner]; }` already exists.
- https://github.com/Dexaran/TokenStandardConverter/blob/5690be8dfb80903d0ea5d553f20b266baf503549/TokenConverter.sol#L90
- https://github.com/Dexaran/TokenStandardConverter/blob/5690be8dfb80903d0ea5d553f20b266baf503549/TokenConverter.sol#L200

4. Variable `empty` is not used
- https://github.com/Dexaran/TokenStandardConverter/blob/5690be8dfb80903d0ea5d553f20b266baf503549/TokenConverter.sol#L220

5. The variables  
https://github.com/Dexaran/TokenStandardConverter/blob/5690be8dfb80903d0ea5d553f20b266baf503549/TokenConverter.sol#L276-L280

should be private (to avoid generating useless getter functions), since the getters already exist:
https://github.com/Dexaran/TokenStandardConverter/blob/5690be8dfb80903d0ea5d553f20b266baf503549/TokenConverter.sol#L283-L311

**Comment by Dexaran** [comment]
>5. The variables erc223Wrappers, erc20Wrappers, erc223Origins, erc20Origins should be private 

Getter functions may have some logic. I would leave this functions public for simplicity of debugging reasons.

**Comment by yuriy77k** [comment]
Of course, for debugging reasons, you can leave it public, especially if you plan to modify existing getter functions. But don't forget to make it private, when publishing Token Converter as a reference code for EIP.
