### ISSUE TITLE
Owner can withdraw all erc20 and erc223 tokens from wrapper contract

### ISSUE THREAD

**Issue by yuriy77k** [Dexaran/TokenStandardConverter#12]
1. When rescuing ERC20 tokens, the `_stuckTokens` is calculated but is not used.
https://github.com/Dexaran/TokenStandardConverter/blob/5690be8dfb80903d0ea5d553f20b266baf503549/TokenConverter.sol#L445

must be:
```Solidity
        safeTransfer(_token, msg.sender, _stuckTokens);
```

2. This function allows the owner to withdraw ERC223 tokens which were deposited to wrap to ERC20. Therefore, to protect users you should add:
```Solidity
        require(address(erc20Wrappers[_token]) == address(0), "ERC223 origin is not allowed");
```

**Comment by Dexaran** [comment]
Fixed https://github.com/Dexaran/TokenStandardConverter/commit/fa01975ed5b624504eaee91e29a1da301ff63034
