### ISSUE TITLE
Wrapper is not compatible with tokens with transfer fee

### ISSUE THREAD

**Issue by yuriy77k** [Dexaran/TokenStandardConverter#13]
Some tokens (like reflecting tokens) take a fee on transfer. So receiver will receive fewer tokens than the sender sends. 

This requirement does not allow to use such tokens
https://github.com/Dexaran/TokenStandardConverter/blob/5690be8dfb80903d0ea5d553f20b266baf503549/TokenConverter.sol#L399-L401

I would recommend replacing this part:
https://github.com/Dexaran/TokenStandardConverter/blob/5690be8dfb80903d0ea5d553f20b266baf503549/TokenConverter.sol#L397-L401

with:
```Solidity
        _amount = IERC20(_ERC20token).balanceOf(address(this)) - _converterBalance;
        erc20Supply[_ERC20token] += _amount;
```

**Comment by Dexaran** [comment]
Fixed https://github.com/Dexaran/TokenStandardConverter/commit/c6ad76e36992b8efd3692ffeee4f27a488673c48
