### ISSUE TITLE
All wrapped tokens has the same name and symbol 

### ISSUE THREAD

**Issue by yuriy77k** [Dexaran/TokenStandardConverter#2]
https://github.com/Dexaran/TokenStandardConverter/blob/c740ceceed8acb632f16b411bcd0b14098f4493d/TokenConverter.sol#L126

I don't think such kind of tokens will be usefull

**Comment by Dexaran** [comment]
No, the token returns origin's `name` , `symbol` and `decimals` like this https://github.com/Dexaran/TokenStandardConverter/blob/main/TokenConverter.sol#L74-L76

The name assignment can be cut away. The name is only assigned internally.

**Comment by yuriy77k** [comment]
I guess you did not get my point. 
In this particular contract `TokenStandardConverter` user can create a wrapped ERC223 token by calling function [createERC223Wrapper](https://github.com/Dexaran/TokenStandardConverter/blob/c740ceceed8acb632f16b411bcd0b14098f4493d/TokenConverter.sol#L122C14-L122C33) with ERC20 token address as a parameter. In a result  a new  `ERC223WrapperToken` will be created with name: `ERC-223-Wrapper`, symbol: `Wrapped Token`, and decimals: `18`, which does not correspondent with the source ERC20 token.

When another user creates a wrapped token for another ERC20 token he will get new token with the same name, symbol and decimals as the first user. And so on.

**Comment by Dexaran** [comment]
Look, I have removed the `name` , `symbol` and `decimelas` from wrappers altogether https://github.com/Dexaran/TokenStandardConverter/commit/636463740c9a2718e26f8fb722ae61f0f9d86fea

It doesn't mean that the token will not return anything however. It just means that the ERC223WrapperToken will not return any values that it store - instead it will call the origin (ERC20 version of the token), ask it's `name` , `symbol` and `decimals` and then return it.
