### ISSUE TITLE
Wrapped tokens did not take into account original decimals

### ISSUE THREAD

**Issue by yuriy77k** [Dexaran/TokenStandardConverter#3]
If the user wraps tokens with decimals different than 18, the wrapped token will have an incorrect representation.
https://github.com/Dexaran/TokenStandardConverter/blob/c740ceceed8acb632f16b411bcd0b14098f4493d/TokenConverter.sol#L122-L131

**Comment by Dexaran** [comment]
Same as https://github.com/Dexaran/TokenStandardConverter/issues/2
