### ISSUE TITLE
Incompatible Transfer event

### ISSUE THREAD

**Issue by yuriy77k** [Dexaran/TokenStandardConverter#4]
https://github.com/Dexaran/TokenStandardConverter/blob/c740ceceed8acb632f16b411bcd0b14098f4493d/TokenConverter.sol#L70

Transfer event has new format (different than in ERC20), so it will not be recognized by current explorers and wallets.

**Comment by Dexaran** [comment]
This was removed as a request of the original EIP editor from @ethereum 

https://github.com/ethereum/EIPs/pull/6485#discussion_r1124874702

**Comment by Dexaran** [comment]
By default there were two events

`event Transfer(address, address, uint256);` and `event TransferData(bytes data);`

it was replaced with just one Transfer event with all the fields since then

**Comment by yuriy77k** [comment]
It's not an issue for token standard if a third-party application will support it. But until that time, tokens transfer will not be recognized by explorers and some of the wallets.

**Comment by Dexaran** [comment]
You are right.
Commited.
