### ISSUE TITLE
Never use function `transfer` and `transferFrom` for arbitrary third-party tokens.

### ISSUE THREAD

**Issue by yuriy77k** [Dexaran/TokenStandardConverter#5]
You are using the function `transfer` and `transferFrom` for any arbitrary tokens (unknown tokens). It's high severity issue. 
You should use `safeTransfer` and `safeTransferFrom` function instead of them 

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f347b410cf6aeeaaf5197e1fece139c793c03b2b/contracts/token/ERC20/utils/SafeERC20.sol#L33-L46

For example, if you deploy this converter on ETH chain and users wrap USDT tokens it will stuck on the contract forever.

Moreover, functions `transfer` and `transferFrom` may return `false` if the sender has insufficient balance (like [DAO token](https://github.com/Dexaran/CallistoDAO/blob/main/DAO2016/DAO.sol#L117). You did not check the return value of `transferFrom` here: 
https://github.com/Dexaran/TokenStandardConverter/blob/c740ceceed8acb632f16b411bcd0b14098f4493d/TokenConverter.sol#L136

So users can mint wrapped tokens even with 0 original tokens on balance.

**Comment by Dexaran** [comment]
>You are using the function transfer and transferFrom for any arbitrary tokens (unknown tokens). It's high severity issue.
You should use safeTransfer and safeTransferFrom function instead of them

A developer is not obligated to implement `safeTransfer` and `safeTransferFrom` functions at all. They are not part of the ERC-20 standard... it is just implementation of the OpenZeppelin and in fact it is not even ERC-20 anymore

**Comment by yuriy77k** [comment]
A developer can use whatever he wants. But you should fix high-severity issues. The way how you do it does not matter.

**Comment by Dexaran** [comment]
Wait, `safeERC20` (which in fact is not safe as it resulted in $1,113B loss) is a library for token developers https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f347b410cf6aeeaaf5197e1fece139c793c03b2b/contracts/token/ERC20/utils/SafeERC20.sol#L33-L46

The functions are internal i.e. I can't call them from my contract anyways. And how does it make `transfer` or `transferFrom` safer?

What high severity issues are you talking about? - The inability to recognize the internal logic of the ERC-20 transfer and whether it `reverts()` or returns `false` on failed transfer?

**Comment by Dexaran** [comment]
This should solve the problem of unknown transferring logic https://github.com/Dexaran/TokenStandardConverter/commit/7330a32019a569dd244b81a39b1cd2846846d6e7

**Comment by yuriy77k** [comment]
safeERC20 take into account the different implementation of ERC20 token (when the functions return `false` or return nothing).
It makes using ERC20 safer, so developers will not make stupid mistakes (like ignoring returns value or expecting bool returns).

**Comment by yuriy77k** [comment]
https://github.com/Dexaran/TokenStandardConverter/blob/7330a32019a569dd244b81a39b1cd2846846d6e7/TokenConverter.sol#L15-L18

You are still expecting to get bool in returns of `transfer` and `transferFrom` functions.

**Comment by yuriy77k** [comment]
If you don't want to use safeERC20 from OpenZeppelin, you can use this code:

```solidity
    function safeTransfer(address token, address to, uint value) internal {
        // bytes4(keccak256(bytes('transfer(address,uint256)')));
        (bool success, bytes memory data) = token.call(abi.encodeWithSelector(0xa9059cbb, to, value));
        require(success && (data.length == 0 || abi.decode(data, (bool))), 'TransferHelper: TRANSFER_FAILED');
    }

    function safeTransferFrom(address token, address from, address to, uint value) internal {
        // bytes4(keccak256(bytes('transferFrom(address,address,uint256)')));
        (bool success, bytes memory data) = token.call(abi.encodeWithSelector(0x23b872dd, from, to, value));
        require(success && (data.length == 0 || abi.decode(data, (bool))), 'TransferHelper: TRANSFER_FROM_FAILED');
    }
```

**Comment by Dexaran** [comment]
>If you don't want to use safeERC20 from OpenZeppelin, you can use this code:

Is it anyhow safer than just ignoring the return values and checking if the balance of the sender changed in the token contract?
I.e. if we know it is a token and a "valid transfer" from out point of view is a situation where user's balance decreased by `_amount` and our balance increased by `_amount` and the transaction did not get `revert()`ed

**Comment by yuriy77k** [comment]
> 



> What high severity issues are you talking about? - The inability to recognize the internal logic of the ERC-20 transfer and whether it `reverts()` or returns `false` on failed transfer?

1. If users wrapped [USDT tokens](https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7#code) they will not be able to unwrap it and function `rescueERC20` will not help. USDT will be stuck on your contract forever (will be lost).
2. Users can receive wrapped tokens without transferring original (like [DAO token](https://github.com/Dexaran/CallistoDAO/blob/main/DAO2016/DAO.sol#L117)). - you already fixed it.

Lossing tokens and minting for free and then withdrawing real tokens that were deposited by other users. 
Aren't these high-severity issues?

**Comment by yuriy77k** [comment]
> > If you don't want to use safeERC20 from OpenZeppelin, you can use this code:
> 
> Is it anyhow safer than just ignoring the return values and checking if the balance of the sender changed in the token contract? I.e. if we know it is a token and a "valid transfer" from out point of view is a situation where user's balance decreased by `_amount` and our balance increased by `_amount` and the transaction did not get `revert()`ed

It will fix the issue with `transferFrom`, but does not fix the issue with `transfer`
try to deploy and test it. I have no time to approve the issue is an issue

**Comment by yuriy77k** [comment]
replace `transfer` with `safeTransfer` here: https://github.com/Dexaran/TokenStandardConverter/blob/9877ec0f197f4ff11ab7d0a6ff6b2b5fbb661d7b/TokenConverter.sol#L167

**Comment by Dexaran** [comment]
Honestly this whole problem looks like a borderline scam. If the standard says "it must return bool" and your implementation returns nothing - then you are just not compatible with the standard. The whole point of having "standards" is to make things predictable and uniform.

Then instead of saying "your token is not compatible with the standard - go re implement it" OpenZeppelin and other devs adopted it. So instead of fixing wrong implementations we force those who work with this wrong tokens to deal with it.

And now everyone has to deal with it. I'm even more confident now that we need to restandardize the token ecosystem.

How things are going now is just purely wrong.

**Comment by Dexaran** [comment]
Fixed https://github.com/Dexaran/TokenStandardConverter/commit/ba97922d7fb243c8bd1feab7388b471b8118be5b

**Comment by yuriy77k** [comment]
> Honestly this whole problem looks like a borderline scam. If the standard says "it must return bool" and your implementation returns nothing - then you are just not compatible with the standard. The whole point of having "standards" is to make things predictable and uniform.
> 
> Then instead of saying "your token is not compatible with the standard - go re implement it" OpenZeppelin and other devs adopted it. So instead of fixing wrong implementations we force those who work with this wrong tokens to deal with it.
> 
> And now everyone has to deal with it. I'm even more confident now that we need to restandardize the token ecosystem.
> 
> How things are going now is just purely wrong.

I guess, Tether ignored reports about this issue. So what community could do? Just adapted to it.

If it was some small unknown project - nobody would worry about adaption. But it's USDT - the most usable token.
