### ISSUE TITLE
medium severity issue in unwrap process

### ISSUE THREAD

**Issue by yuriy77k** [Dexaran/TokenStandardConverter#6]
When a user sends wrapped tokens to contract to [unwrap](https://github.com/Dexaran/TokenStandardConverter/blob/2d297bced3b34dd439b66d8b6256f626bcb2b999/TokenConverter.sol#L112-L120) it, the value of `erc20Supply[_ERC20token]` was not decreased by unwrap amount.

**Comment by Dexaran** [comment]
Fixed https://github.com/Dexaran/TokenStandardConverter/commit/0f8e53c5c3ec6849ba659da5ceee65bf9677fbda
