### ISSUE TITLE
wasting of gas in function convertERC20toERC223

### ISSUE THREAD

**Issue by yuriy77k** [Dexaran/TokenStandardConverter#7]
You don't need to check `balanceOf(msg.sender)` before and after the token transfer. Removing these calls will save about 5K gas. 
https://github.com/Dexaran/TokenStandardConverter/blob/2d297bced3b34dd439b66d8b6256f626bcb2b999/TokenConverter.sol#L136-L144

The contract should check only own balance `balanceOf(address(this))`. The contract should mint the amount which it receives. Does not matter what msg.sender balance is.

**Comment by Dexaran** [comment]
You are right

https://github.com/Dexaran/TokenStandardConverter/commit/9877ec0f197f4ff11ab7d0a6ff6b2b5fbb661d7b
